######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 4 17:15:56 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gen_uninstall.cc

RC_FILE = gen_uninstall.rc
