######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 4 17:15:56 2010
######################################################################

TEMPLATE = app
TARGET = gen_uninstall
DEPENDPATH += .
INCLUDEPATH += .

QT += core5compat core
CONFIG+=utf8_source
# Input
SOURCES += gen_uninstall.cc

#RC_FILE = gen_uninstall.rc
